/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export { CardStyleTypeEnum, CardTypeEnum, MediaTypeEnum } from './src/main/ets/model/CardData';

export { BannerData, BannerTypeEnum, BANNER_SCALE_FACTOR, TITLE_SCALE_FACTOR } from './src/main/ets/model/BannerData';

export { BaseData } from './src/main/ets/model/BaseData';

export {
  ArticleDetailParams,
  ComponentDetailParams,
  HomeListParams,
  SampleDetailParams,
  CodeViewParams
} from './src/main/ets/model/RouterParams';

export { BaseDetailParam, BaseListParam } from './src/main/ets/model/BaseParam';

export { BannerCard } from './src/main/ets/component/BannerCard';

export { BannerItem } from './src/main/ets/component/BannerItem';

export { BaseDetailComponent } from './src/main/ets/component/BaseDetailComponent';

export { LoadingMoreItemBuilder } from './src/main/ets/component/LoadingMoreItem';

export {
  BaseHomeViewModel,
  BaseHomeEventType,
  BaseHomeEventParam,
  CalculateHeightParam,
  InitializeParam,
  TabBarAnimationParam,
  OffsetParam
} from './src/main/ets/viewmodel/BaseHomeViewModel';

export { BannerSource } from './src/main/ets/viewmodel/BannerSource';

export { TabBarType, TAB_CONTENT_STATUSES } from './src/main/ets/model/TabStatusBarModel';

export { BaseHomeState, BannerState } from './src/main/ets/viewmodel/BaseHomeState';

export { BaseHomeView } from './src/main/ets/view/BaseHomeView';

export { TagTipLabel } from './src/main/ets/component/TagLabel';