/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ArticleListItem } from './FormCardInfo';

export const ALL_ARTICLE_LISTS: ArticleListItem[] = [
  {
    id: 1,
    title: '小窗口大世界，智享实况窗服务',
    desc: '实时信息随处展示。',
    detailsUrl: 'articlecols/articles/live-window-service/index.html',
    name: '开发实践',
    isArticle: true,
  },
  {
    id: 2,
    title: 'Picker安心取，用户主导安全新体验',
    desc: '纯净安全，打造全新体验。',
    detailsUrl: 'articlecols/articles/native-safety/index.html',
    name: '开发实践',
    isArticle: true,
  },
  {
    id: 3,
    title: '一镜到底，畅享无界丝滑视觉之旅',
    desc: '极致流畅，畅享丝滑。',
    detailsUrl: 'articlecols/articles/shared-element-transition/index.html',
    name: '开发实践',
    isArticle: true,
  },
  {
    id: 4,
    title: '跨设备互联，打造无缝流转极致体验',
    desc: '跨设备互联，无缝流转。',
    detailsUrl: 'articlecols/articles/app-continuation/index.html',
    name: '开发实践',
    isArticle: true,
  },
  {
    id: 5,
    title: 'AI识图，开启智能图像处理新纪元',
    desc: '开启图像智能新纪元。',
    detailsUrl: 'articlecols/articles/smart-visual-recognition/index.html',
    name: '开发实践',
    isArticle: true,
  },
  {
    id: 18,
    title: '多端UX设计',
    desc: '提供特征型场景界面设计，结合应用业务场景，实现最佳界面适配和创新设计。',
    detailsUrl: 'articlecols/articles/native-ux-design/index.html',
    name: '应用体验设计',
    isArticle: true,
  },
  {
    id: 22,
    title: '应用UX体验标准',
    desc: '提前了解HarmonyOS应用UX体验标准，快速满足上架条件。',
    detailsUrl: 'articlecols/articles/ux-guidelines/index.html',
    name: '应用体验设计',
    isArticle: true,
  },
  {
    id: 7,
    title: 'UX动效设计',
    desc: 'HarmonyOS UX动效设计，通过适配不同场景，提升用户体验，满足多样化需求。',
    detailsUrl: 'articlecols/articles/design-animation/index.html',
    name: '应用体验设计',
    isArticle: true,
  },
  {
    id: 8,
    title: '分层架构设计',
    desc: 'HarmonyOS应用采用分层架构，一套代码工程，支持华为手机、PC/2in1等1+8全场景设备。',
    detailsUrl: 'articlecols/articles/layered-architecture-design/index.html',
    name: '功能开发',
    isArticle: true,
  },
  {
    id: 12,
    title: 'HMOS代码工坊一多开发实践',
    desc: '践行“一次开发，多端部署”理念，实现多设备无缝协同，提供一致且高效的用户体验。',
    detailsUrl: 'articlecols/articles/multi-adaptation/index.html',
    name: '功能开发',
    isArticle: true,
  }
];