/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ConfigurationConstant } from '@kit.AbilityKit';
import { curves } from '@kit.ArkUI';
import {
  BreakpointType,
  CommonConstants,
  GlobalInfoModel,
  Logger,
  StorageKey,
  TRACK_KEY,
  TrackServiceData,
  WebNodeController,
  WebUtil,
  InteractionTypeEnum,
  ActionName,
} from '@ohos/common';
import { CodePreviewComponent } from './CodePreviewComponent';
import type { ConfigInterface } from '../componentdetailview/ComponentDetailConfig';
import { ComponentDetailPageVM, TopNavigationChangeEvent } from '../viewmodel/ComponentDetailPageVM';
import type { ComponentDetailState } from '../viewmodel/ComponentDetailState';
import { ComponentDetailManager } from '../viewmodel/ComponentDetailManager';
import { DetailPageConstant } from '../constant/DetailPageConstant';
import { CodePreviewJSUtil } from '../util/CodePreviewJSUtil';
import { AttributeChangeArea } from './AttributeChangeArea';
import { RecommendList } from './RecommendList';

const PREVIEW_HEIGHT_SM: number = DetailPageConstant.PREVIEW_HEIGHT_SM;
const TAG: string = '[DetailContentView]';

@Component
export struct DetailContentView {
  @ObjectLink componentDetailState: ComponentDetailState;
  @Prop componentName: string;
  @StorageProp(StorageKey.GLOBAL_INFO) @Watch('handleBreakPointChange') globalInfoModel: GlobalInfoModel =
    AppStorage.get(StorageKey.GLOBAL_INFO) ?? new GlobalInfoModel();
  @StorageProp(StorageKey.COLOR_MODE) systemColorMode: ConfigurationConstant.ColorMode =
    AppStorage.get(StorageKey.COLOR_MODE) ?? ConfigurationConstant.ColorMode.COLOR_MODE_NOT_SET;
  @State isShowCodePreview: boolean = false;
  @State scaleValue: number = 1;
  @State showDivider: boolean = false;
  @State isShowTopDivider: boolean = false;
  @State webNodeController?: WebNodeController = undefined;
  scroller: Scroller = new Scroller();
  private viewModel?: ComponentDetailPageVM =
    ComponentDetailManager.getInstance().getDetailViewModel(this.componentName);
  private paddingToTop: number = 0;
  private paddingToBottom: number = 36;
  private detailConfig: Record<string, ConfigInterface> = AppStorage.get(StorageKey.COMPONENT_CONFIG) ?? {};

  @Builder
  textTip(text: ResourceStr) {
    Text(text)
      .fontSize($r('sys.float.Subtitle_S'))
      .fontColor($r('sys.color.font_secondary'))
      .fontWeight(FontWeight.Regular)
      .margin({
        top: $r('app.float.comp_detail_area_title_top'),
        bottom: $r('sys.float.padding_level4'),
      })
  }

  aboutToAppear(): void {
    this.webNodeController = WebUtil.getWebNode(WebUtil.getComponentCodeUrl()) as WebNodeController;
    this.paddingToBottom =
      this.globalInfoModel.naviIndicatorHeight === 0 ? 36 : this.globalInfoModel.naviIndicatorHeight;
    // In EntryAbility, set decorHeight 0.
    const decorHeight: number =
      this.globalInfoModel.widthBreakpoint !== WidthBreakpoint.WIDTH_XL ? this.globalInfoModel.decorHeight : 0;
    this.paddingToTop = this.globalInfoModel.statusBarHeight === decorHeight ? 0 : this.globalInfoModel.statusBarHeight;
  }

  aboutToDisappear(): void {
    try {
      const webController = WebUtil.getWebController(WebUtil.getComponentCodeUrl());
      webController?.scrollTo(0, 0);
    } catch {
      Logger.error(TAG, `WebController scroll to zero failed.`);
    }
  }

  jumpCodePreviewView() {
    const code = this.componentDetailState.code;
    const viewModel: ComponentDetailPageVM | undefined =
      ComponentDetailManager.getInstance().getDetailViewModel(this.componentName);
    WebUtil.downPage(WebUtil.getComponentCodeUrl());
    this.webNodeController = undefined;
    const toFullScreenMethod: string = 'toFullScreen()';
    CodePreviewJSUtil.codeViewRunJS(toFullScreenMethod);
    this.getUIContext().animateTo({ curve: curves.interpolatingSpring(0, 1, 195, 23) }, () => {
      viewModel?.jumpToCodePreview(code, () => {
        this.backFromCodePreview();
      });
    });
  }

  backFromCodePreview(): void {
    this.webNodeController = WebUtil.getWebNode(WebUtil.getComponentCodeUrl()) as WebNodeController;
    this.webNodeController?.add();
  }

  handleBreakPointChange() {
    this.viewModel?.sendEvent(new TopNavigationChangeEvent(this.globalInfoModel.widthBreakpoint ===
    WidthBreakpoint.WIDTH_SM ? false : this.isShowTopDivider));
  }

  build() {
    Flex({
      direction: this.globalInfoModel.widthBreakpoint === WidthBreakpoint.WIDTH_SM ? FlexDirection.Column :
        FlexDirection.Row,
    }) {
      Column() {
        this.textTip($r('app.string.preview'))
        Column() {
          (this.detailConfig?.[this.componentName] as ConfigInterface)?.previewComponentBuilder.builder({
            descriptor: this.componentDetailState.descriptor,
          })
        }
        .backgroundColor($r('sys.color.comp_background_primary'))
        .justifyContent(FlexAlign.Center)
        .width('100%')
        .height(new BreakpointType({
          sm: DetailPageConstant.PREVIEW_SUB_HEIGHT_SM,
          md: (this.globalInfoModel.deviceHeight - (CommonConstants.NAVIGATION_HEIGHT + this.paddingToTop +
          this.paddingToBottom) - DetailPageConstant.TEXT_TIP_HEIGHT),
          lg: (this.globalInfoModel.deviceHeight - (CommonConstants.NAVIGATION_HEIGHT + this.paddingToTop +
          this.paddingToBottom) - DetailPageConstant.TEXT_TIP_HEIGHT),
        }).getValue(this.globalInfoModel.widthBreakpoint))
        .borderRadius($r('sys.float.corner_radius_level8'))
      }
      .padding({
        top: CommonConstants.NAVIGATION_HEIGHT + this.globalInfoModel.statusBarHeight,
        left: new BreakpointType({
          sm: $r('sys.float.padding_level8'),
          md: $r('sys.float.padding_level12'),
          lg: $r('sys.float.padding_level16'),
        }).getValue(this.globalInfoModel.widthBreakpoint),
        right: new BreakpointType({
          sm: $r('sys.float.padding_level8'),
          md: $r('sys.float.padding_level4'),
          lg: $r('sys.float.padding_level6'),
        }).getValue(this.globalInfoModel.widthBreakpoint),
        bottom: new BreakpointType({
          sm: $r('sys.float.padding_level4'),
          md: $r('sys.float.padding_level0'),
          lg: $r('sys.float.padding_level0'),
        }).getValue(this.globalInfoModel.widthBreakpoint)
      })
      .size(this.globalInfoModel.widthBreakpoint === WidthBreakpoint.WIDTH_SM ? { width: '100%' } : { width: '50%' })
      .alignItems(HorizontalAlign.Start)

      if (this.globalInfoModel.widthBreakpoint === WidthBreakpoint.WIDTH_SM && this.showDivider) {
        Divider()
          .width('100%')
      }
      Scroll(this.scroller) {
        Column() {
          if (this.componentDetailState.attributes.length !== 0) {
            this.textTip($r('app.string.changeAttributes'))
            AttributeChangeArea({
              attributes: this.componentDetailState.attributes,
              componentName: this.componentName,
            })
          }
          this.textTip($r('app.string.code'))
          CodePreviewComponent({
            webNodeController: this.webNodeController,
            code: this.componentDetailState.code,
            componentName: this.componentName,
            pageContainer: false,
            isDarkMode: (this.systemColorMode === ConfigurationConstant.ColorMode.COLOR_MODE_DARK),
            pushPage: () => {
              this.jumpCodePreviewView();
            },
          })
            .width('100%')
            .height($r('app.float.code_preview_height'))
            .geometryTransition(CommonConstants.CODE_PREVIEW_GEOMETRY_ID, { follow: true })
            .borderRadius($r('sys.float.corner_radius_level8'))
            .clip(true)
            .onClick(() => {
              this.jumpCodePreviewView();
            })
            .customProperty(TRACK_KEY, {
              interactionContent: this.componentName,
              interactionType: InteractionTypeEnum.COMPONENT,
              actionName: ActionName.CODE_CLICK,
            } as TrackServiceData)
          if (this.componentDetailState?.recommends?.length > 0) {
            this.textTip($r('app.string.recommend'))
            RecommendList({ recommends: this.componentDetailState.recommends })
              .customProperty(TRACK_KEY, {
                interactionContent: this.componentName,
                interactionType: InteractionTypeEnum.COMPONENT,
                actionName: ActionName.RECOMMEND_CLICK,
              } as TrackServiceData)
          }
        }
        .alignItems(HorizontalAlign.Start)
        .padding({
          top: new BreakpointType({
            sm: 0,
            md: CommonConstants.NAVIGATION_HEIGHT + this.globalInfoModel.statusBarHeight,
            lg: CommonConstants.NAVIGATION_HEIGHT + this.globalInfoModel.statusBarHeight,
          }).getValue(this.globalInfoModel.widthBreakpoint),
          bottom: this.paddingToBottom,
        })
      }
      .align(Alignment.Top)
      .scrollBar(BarState.Off)
      .edgeEffect(EdgeEffect.Spring)
      .onDidScroll(() => {
        if (this.scroller.currentOffset().yOffset > DetailPageConstant.SCROLL_OFFSET_Y) {
          if (!this.showDivider) {
            this.showDivider = true;
          }
          this.isShowTopDivider = (this.globalInfoModel.widthBreakpoint !== WidthBreakpoint.WIDTH_SM);
          this.viewModel?.sendEvent(new TopNavigationChangeEvent(this.isShowTopDivider));
        } else if (this.scroller.currentOffset().yOffset <= DetailPageConstant.SCROLL_OFFSET_Y) {
          this.showDivider = false;
          this.isShowTopDivider = false;
          this.viewModel?.sendEvent(new TopNavigationChangeEvent(this.isShowTopDivider));
        }
      })
      .nestedScroll({
        scrollForward: NestedScrollMode.SELF_ONLY,
        scrollBackward: NestedScrollMode.SELF_ONLY,
      })
      .layoutWeight(1)
      .size(this.globalInfoModel.widthBreakpoint === WidthBreakpoint.WIDTH_SM ?
        {
          width: '100%',
          height: (this.globalInfoModel.deviceHeight - PREVIEW_HEIGHT_SM -
            (CommonConstants.NAVIGATION_HEIGHT + this.paddingToTop)),
        } :
        {
          width: '50%',
          height: '100%',
        })
      .padding({
        left: new BreakpointType({
          sm: $r('sys.float.padding_level8'),
          md: $r('sys.float.padding_level4'),
          lg: $r('sys.float.padding_level6'),
        }).getValue(this.globalInfoModel.widthBreakpoint),
        right: new BreakpointType({
          sm: $r('sys.float.padding_level8'),
          md: $r('sys.float.padding_level12'),
          lg: $r('sys.float.padding_level16'),
        }).getValue(this.globalInfoModel.widthBreakpoint),
      })
    }
    .width('100%')
    .height('100%')
  }
}