/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class TripData {
  /**
   * Start time.
   */
  public startTime: string;
  /**
   * End time.
   */
  public endTime: string;
  /**
   * Calendar date.
   */
  public date: ResourceStr;
  /**
   * Conflict or not.
   */
  public conflicting: boolean | undefined = false;
  /**
   * Location.
   */
  public location: string | undefined;

  /**
   * constructor method.
   */
  constructor(startTime: string, endTime: string, date: ResourceStr, conflicting?: boolean, location?: string) {
    this.date = date;
    this.startTime = startTime;
    this.endTime = endTime;
    this.conflicting = conflicting;
    this.location = location;
  }
}