/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum PageEnum {
  MAIN_PAGE = 'MainPage',
  COMPONENT_LIST_VIEW = 'ComponentListView',
  COMPONENT_DETAIL_VIEW = 'ComponentDetailView',
  PRACTICES_VIEW = 'PracticesView',
  SAMPLE_DETAIL_VIEW = 'SampleDetailView',
  BANNER_DETAIL_VIEW = 'BannerDetailView',
  CODE_PREVIEW_VIEW = 'CodePreviewView',
  PEN_KIT_VIEW = 'PenKitView',
  EXPLORATION_VIEW = 'ExplorationView',
  ARTICLE_DETAIL_VIEW = 'ArticleDetailView',
  MINE_VIEW = 'MineView',
  NEW_CONTENT_VIEW = 'NewContentView',
  ABOUT_VIEW = 'AboutView',
  WEARABLE_SOURCE_CODE_VIEW = 'WearableSourceCodeView',
  TV_SETTINGS_VIEW = 'TvSettingsView',
  TV_SOURCECODE_VIEW = 'TvSourceView',
  TV_ABOUT_VIEW = 'TvAboutView',
  IMAGE_PREVIEW = 'ImagePreview'
}