/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { common, StartOptions, Want } from '@kit.AbilityKit';
import type { BusinessError } from '@kit.BasicServicesKit';
import Logger from './Logger';

const TAG = '[ProcessUtil]';

export class ProcessUtil {
  public static startAbility(context: common.UIAbilityContext, want: Want, options?: StartOptions): Promise<boolean> {
    try {
      if (!context) {
        Logger.error(TAG, `startAbility failed, cause context is null or undefined.`);
        return Promise.resolve(false);
      }
      return context.startAbility(want, options).then(() => {
        Logger.info(TAG, 'startAbility succeed');
        return true;
      }).catch((err: BusinessError) => {
        Logger.error(TAG, `startAbility failed, cause ${err.code}, ${err.message}`);
        return false;
      });
    } catch (error) {
      const err: BusinessError = error as BusinessError;
      Logger.error(TAG, `startAbility failed error: ${err.code}, ${err.message}`);
      return Promise.resolve(false);
    }
  }
}