/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export enum InsightIntentEventTypeEnum {
  JUMP_TO_MAIN = 'jumpToMainPage',
  JUMP_TO_COMPONENT = 'jumpToComponentDetailPage',
  JUMP_TO_SAMPLE = 'jumpToSampleDetailPage',
  JUMP_TO_PRACTICE = 'jumpToPracticeArticlePage'
}

export enum InsightIntentNameEnum {
  JUMP_FUNCTION_PAGE = 'JumpFunctionPage',
  JUMP_STUDY_PAGE = 'LearnCourse'
}

export enum IntentNameEnum {
  JMP_FN_PAGE = 'JumpFunctionPage',
  JMP_STUDY_PAGE = 'LearnCourse'
}