/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** Use these variables when you tailor your code. They must be of the const type. */
export const INTENT_NAME = 'LearnCourse';
export const INTENT_VERSION = '1.0.2';
export const INTENT_XIAOYI_DEFAULT_VALUE = 'XIAOYI_EXTRACTED_NO_PARAM';
export const INTENT_TOAST_DURATION_WHEN_XIAOYI_FAILED = 10000;