/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class PaddingToken {
  /**
   * Padding: 0vp
   */
  public static readonly PADDING_0VP: number = 0;

  /**
   * Padding: 2vp
   */
  public static readonly PADDING_2VP: number = 2;

  /**
   * Padding: 3vp
   */
  public static readonly PADDING_3VP: number = 3;

  /**
   * Padding: 4vp
   */
  public static readonly PADDING_4VP: number = 4;

  /**
   * Padding: 5vp
   */
  public static readonly PADDING_5VP: number = 5;

  /**
   * Padding: 6vp
   */
  public static readonly PADDING_6VP: number = 6;

  /**
   * Padding: 8vp
   */
  public static readonly PADDING_8VP: number = 8;

  /**
   * Padding: 10vp
   */
  public static readonly PADDING_10VP: number = 10;

  /**
   * Padding: 11vp
   */
  public static readonly PADDING_11VP: number = 11;

  /**
   * Padding: 12vp
   */
  public static readonly PADDING_12VP: number = 12;

  /**
   * Padding: 12.75vp
   */
  public static readonly PADDING_12_point_75VP: number = 12.75;

  /**
   * Padding: 14vp
   */
  public static readonly PADDING_14VP: number = 14;

  /**
   * Padding: 16vp
   */
  public static readonly PADDING_16VP: number = 16;

  /**
   * Padding: 18vp
   */
  public static readonly PADDING_18VP: number = 18;

  /**
   * Padding: 20vp
   */
  public static readonly PADDING_20VP: number = 20;

  /**
   * Padding: 22vp
   */
  public static readonly PADDING_22VP: number = 22;

  /**
   * Padding: 22.75vp
   */
  public static readonly PADDING_22_point_75VP: number = 22.75;

  /**
   * Padding: 24vp
   */
  public static readonly PADDING_24VP: number = 24;

  /**
   * Padding: 26vp
   */
  public static readonly PADDING_26VP: number = 26;

  /**
   * Padding: 28vp
   */
  public static readonly PADDING_28VP: number = 28;

  /**
   * Padding: 30vp
   */
  public static readonly PADDING_30VP: number = 30;

  /**
   * Padding: 32vp
   */
  public static readonly PADDING_32VP: number = 32;

  /**
   * Padding: 34vp
   */
  public static readonly PADDING_34VP: number = 34;

  /**
   * Padding: 36vp
   */
  public static readonly PADDING_36VP: number = 36;

  /**
   * Padding: 40vp
   */
  public static readonly PADDING_40VP: number = 40;

  /**
   * Padding: 42vp
   */
  public static readonly PADDING_42VP: number = 42;

  /**
   * Padding: 44vp
   */
  public static readonly PADDING_44VP: number = 44;

  /**
   * Padding: 48vp
   */
  public static readonly PADDING_48VP: number = 48;

  /**
   * Padding: 50vp
   */
  public static readonly PADDING_50VP: number = 50;

  /**
   * Padding: 56vp
   */
  public static readonly PADDING_56VP: number = 56;

  /**
   * Padding: 64vp
   */
  public static readonly PADDING_64VP: number = 64;

  /**
   * Padding: 68vp
   */
  public static readonly PADDING_68VP: number = 68;

  /**
   * Padding: 76vp
   */
  public static readonly PADDING_76VP: number = 76;

  /**
   * Padding: 80vp
   */
  public static readonly PADDING_80VP: number = 80;

  /**
   * Padding: 160vp
   */
  public static readonly PADDING_160VP: number = 160;
}
