/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum TriggerEnums {
  // Component
  COMPONENT_BANNER = 'component-banner',
  COMPONENT_PAGE = 'component-page',
  COMPONENT_DETAIL = 'component-details',
  // Sample
  SAMPLE_PAGE = 'sample-page',
  SAMPLE_LIST = 'sample-list',
  SAMPLE_DETAILS = 'sample-details',
  // Discover
  DISCOVER_PAGE = 'discovery-page',
  DISCOVER_ARTICLE = 'discovery-article',
  // Mine
  NEW_CONTENTS = 'new-contents',

  //Wearable
  WEARABLE_SAMPLE_TRIGGER = 'wearable-sample-list',

  //Version
  VERSION_SAMPLE_TRIGGER = 'vision-sample-list',

  //Track
  TRACK_POST_TRIGGER = 'track-post',
}