/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { media } from '@kit.MediaKit';
import List from '@ohos.util.List';

class BasicDataSource implements IDataSource {
  private listeners: DataChangeListener[] = [];

  public totalCount(): number {
    return 0;
  }

  public getData(_index: number): media.AVFileDescriptor | string | undefined {
    return undefined;
  }

  registerDataChangeListener(listener: DataChangeListener): void {
    if(this.listeners.indexOf(listener) < 0){
      this.listeners.push(listener)
    }
  }

  unregisterDataChangeListener(listener: DataChangeListener): void {
    const pos = this.listeners.indexOf(listener);
    if(pos >= 0) {
      this.listeners.splice(pos,1);
    }
  }

  notifyDataReload(): void {
    this.listeners.forEach(listener => {
      listener.onDataReloaded();
    })
  }

  notifyDataAdd(index:number): void {
    this.listeners.forEach(listeners => {
      listeners.onDataAdd(index);
    })
  }

  notifyDataChange(index:number): void {
    this.listeners.forEach(listener => {
      listener.onDataChange(index);
    })
  }
}

export class MyDataSource extends BasicDataSource {
  public dataArray: string[] = [];

  constructor(ele: Object[]) {
    super();
    for(let index = 0;index < ele.length; index++){
      this.dataArray.push(ele[index] as string);
    }
  }

  public totalCount(): number {
    return this.dataArray.length
  }

  public getData(index: number): string {
    return this.dataArray[index];
  }

  public addData(index: number): void {
    this.dataArray.splice(index, 0);
    this.notifyDataAdd(index);
  }
}