/*
* Copyright (c) 2026 Huawei Device Co., Ltd.
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

export class CommonConstants {
  /**
   * API version 22 supported by the device
   */
  public static readonly API_VERSION_22: number = 60020;
  /**
   * API version 23 supported by the device
   */
  public static readonly API_VERSION_23: number = 60100;
  /**
   * Tab home page index
   */
  public static readonly TAB_HOME_INDEX: number = 0;
  /**
   * Tab hot page index
   */
  public static readonly TAB_HOT_PAGE_INDEX: number = 1;
  /**
   * Tab video page index
   */
  public static readonly TAB_VIDEO_PAGE_INDEX: number = 2;
  /**
   * Tab mine page index
   */
  public static readonly TAB_MINE_PAGE_INDEX: number = 3;
  /**
   * Device type pc
   */
  public static readonly DEVICE_TYPE_PC: string = 'multicommunityapplicationpcsample';
  /**
   * PC decor height
   */
  public static readonly PC_DECOR_HEIGHT: number = 56;
  /**
   * PC STATUS BAR ICON SIZE
   */
  public static readonly PC_STATUS_BAR_ICON_SIZE: number = 24;
}