/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { BaseState, BaseVM, Logger, PageContext, PageEnum, PreferenceManager } from '@ohos/common';

const TAG: string = '[SplashViewModel]';

export class SplashViewModel extends BaseVM<BaseState> {
  private pageContext = AppStorage.get<PageContext>('pageContext');
  private preferenceManager: PreferenceManager = PreferenceManager.getInstance();

  public constructor() {
    super(new BaseState());
  }

  public sendEvent(eventType: SplashEventTypeEnum): void {
    if (eventType === SplashEventTypeEnum.JUMP_TO_MAIN) {
      this.jumpToMainPage();
    } else if (eventType === SplashEventTypeEnum.CHECK_FIRST_START) {
      this.checkIsFirstStart();
    }
  }

  private jumpToMainPage(): void {
    this.pageContext?.replacePage({
      routerName: PageEnum.MAIN_PAGE,
    });
  }

  private checkIsFirstStart(): void {
    const hasValue: boolean = this.preferenceManager.hasValue('isFirstStart');
    if (hasValue) {
      Logger.info(TAG, 'Not first startup.');
    } else {
      Logger.info(TAG, 'First startup.');
      this.preferenceManager.setValue('isFirstStart', false);
    }
  }
}

export enum SplashEventTypeEnum {
  JUMP_TO_MAIN = 'jumpToMainPage',
  CHECK_FIRST_START = 'checkIsFirstStart',
}