/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ArcList, ArcListItem, LengthMetrics, ComponentContent } from '@kit.ArkUI';
import { ImageUtil } from '@ohos/common';
import { MediaTypeEnum } from '@ohos/commonbusiness';
import { WearableSampleData } from '../model/WearableSampleData';
import { SampleListState } from '../viewmodel/SampleListState';
import {
  LoadSampleParam,
  SampleListEventType,
  SampleListViewModel,
  SourceCodeLinkPageParam
} from '../viewmodel/SampleListViewModel';

const ITEM_SPACE: number = 6;
const ITEM_WIDTH: string = '88%';

@Builder
function SampleListHeader() {
  Column() {
    Text($r('app.string.sample_library'))
      .fontSize($r('app.float.item_title_size'))
      .fontWeight(FontWeight.Bold)
      .fontColor($r('sys.color.font_on_primary'))
      .padding({
        top: $r('sys.float.padding_level3'),
        bottom: $r('sys.float.padding_level2'),
      })
    Text($r('app.string.watch_development_sample'))
      .fontSize($r('sys.float.Subtitle_M'))
      .fontWeight(FontWeight.Regular)
      .fontColor($r('sys.color.font_on_secondary'))
  }
}

@Component
export struct SampleListView {
  context: UIContext = this.getUIContext();
  sampleListHeader: ComponentContent<[]> = new ComponentContent(this.context, wrapBuilder(SampleListHeader));
  viewModel: SampleListViewModel = SampleListViewModel.getInstance();
  @State sampleListState: SampleListState = this.viewModel.getState();

  aboutToAppear(): void {
    this.viewModel.sendEvent<null>({
      type: SampleListEventType.LOAD_SAMPLE_LIST,
    });
  }

  @Builder
  SampleListItem(wearableSampleData: WearableSampleData) {
    Row() {
      if (wearableSampleData.mediaType === MediaTypeEnum.SYMBOL) {
        Button({ type: ButtonType.Circle }) {
          SymbolGlyph($r(wearableSampleData.mediaInfoList[0].mediaUrl))
            .fontSize($r('app.float.icon_size'))
            .fontColor([$r('sys.color.font_on_primary')])
        }
        .width($r('app.float.button_size'))
        .height($r('app.float.button_size'))
        .backgroundColor(wearableSampleData.symbolGlyphColor)
      } else if (wearableSampleData.mediaType == MediaTypeEnum.IMAGE) {
        Image(ImageUtil.getImgResource(wearableSampleData.mediaInfoList[0].mediaUrl))
          .width($r('app.float.button_size'))
          .height($r('app.float.button_size'))
      }

      Column() {
        Text(wearableSampleData.title)
          .fontWeight(FontWeight.Medium)
          .fontColor($r('sys.color.font_on_primary'))
          .fontSize($r('app.float.item_title_size'))
        Text(wearableSampleData.desc)
          .fontWeight(FontWeight.Regular)
          .fontColor($r('sys.color.font_on_secondary'))
          .fontSize($r('app.float.item_description_size'))
      }

      SymbolGlyph($r('sys.symbol.chevron_forward'))
        .fontSize($r('app.float.icon_size'))
        .fontColor([$r('sys.color.icon_secondary')])
    }
    .justifyContent(FlexAlign.SpaceBetween)
    .width(ITEM_WIDTH)
    .borderRadius($r('app.float.item_border_radius'))
    .padding({
      top: $r('sys.float.padding_level6'),
      bottom: $r('sys.float.padding_level5'),
      left: $r('sys.float.padding_level3'),
      right: $r('sys.float.padding_level3'),
    })
    .backgroundColor($r('app.color.item_background'))
    .onClick(() => {
      if (wearableSampleData.isSourceCode === true) {
        this.viewModel.sendEvent<SourceCodeLinkPageParam>({
          type: SampleListEventType.JUMP_TO_SOURCE_CODE_LINK_PAGE,
          param: {
            sourceCodeLink: wearableSampleData.originalUrl,
            title: wearableSampleData.title
          }
        })
      } else {
        this.viewModel.sendEvent<LoadSampleParam>({
          type: SampleListEventType.LOAD_SAMPLE,
          param: {
            abilityName: wearableSampleData.abilityName,
            apiVersion: wearableSampleData.apiVersion,
          }
        });
      }
    })
  }

  build() {
    ArcList({ header: this.sampleListHeader }) {
      ForEach(this.sampleListState.wearableSampleList, (item: WearableSampleData) => {
        ArcListItem() {
          this.SampleListItem(item)
        }
      }, (item: WearableSampleData) => item.id.toString())
    }
    .space(LengthMetrics.vp(ITEM_SPACE))
    .focusable(true)
    .focusOnTouch(true)
    .defaultFocus(true)
  }
}