/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  BreakpointType,
  CommonConstants,
  GlobalInfoModel,
  ImageComponent,
  InteractionTypeEnum,
  StorageKey,
  TRACK_KEY,
  TrackNode,
  TrackServiceData,
  HdsUtil,
} from '@ohos/common';
import { TagTipLabel } from '@ohos/commonbusiness';
import { SampleCardData, SampleContent } from '../model/SampleData';
import { TagLabel } from './TagLabel';

const ITEM_HEIGHT: number = 340;
const ITEM_ASPECT: number = 0.74;
const LOG_MAX_WIDTH: number = 202;
const DISPLAY_COUNT: number = 3;
const MARGIN_COUNT: number = 2;

@Component
export struct SampleScrollCard {
  @StorageProp(StorageKey.GLOBAL_INFO) @Watch('handleBreakPointChange') globalInfoModel: GlobalInfoModel =
    AppStorage.get(StorageKey.GLOBAL_INFO) ?? new GlobalInfoModel();
  @Prop sampleCardData: SampleCardData;
  handleItemClick?: Function;
  @State sampleItemWidth: number = ITEM_HEIGHT * ITEM_ASPECT;
  @State horizontalPadding: Resource = new BreakpointType({
    sm: $r('sys.float.padding_level8'),
    md: $r('sys.float.padding_level12'),
    lg: $r('sys.float.padding_level16'),
  }).getValue(this.globalInfoModel.widthBreakpoint);
  @State contentOffset: number = new BreakpointType({
    sm: CommonConstants.SPACE_16,
    md: CommonConstants.SPACE_24,
    lg: CommonConstants.SPACE_32,
  }).getValue(this.globalInfoModel.widthBreakpoint);

  aboutToAppear(): void {
    this.handleBreakPointChange();
  }

  handleBreakPointChange() {
    const barWidth =
      AppStorage.get<boolean>(StorageKey.IS_SIDEBAR_LAYOUT) ? CommonConstants.SIDE_BAR_WIDTH :
        (HdsUtil.isSupportNewMaterialApi() ? 0 : CommonConstants.TAB_BAR_WIDTH);
    this.horizontalPadding = new BreakpointType({
      sm: $r('sys.float.padding_level8'),
      md: $r('sys.float.padding_level12'),
      lg: $r('sys.float.padding_level16'),
    }).getValue(this.globalInfoModel.widthBreakpoint);
    this.contentOffset = new BreakpointType({
      sm: CommonConstants.SPACE_16,
      md: CommonConstants.SPACE_24,
      lg: CommonConstants.SPACE_32,
    }).getValue(this.globalInfoModel.widthBreakpoint);
    if (this.globalInfoModel.widthBreakpoint === WidthBreakpoint.WIDTH_LG ||
      this.globalInfoModel.widthBreakpoint === WidthBreakpoint.WIDTH_XL ||
      AppStorage.get<boolean>(StorageKey.IS_SIDEBAR_LAYOUT)) {
      this.sampleItemWidth = (this.globalInfoModel.deviceWidth - barWidth - CommonConstants.SPACE_32 * MARGIN_COUNT -
        CommonConstants.SPACE_16 * (DISPLAY_COUNT - 1)) / DISPLAY_COUNT;
    } else {
      this.sampleItemWidth = ITEM_HEIGHT * ITEM_ASPECT;
    }
  }

  @Builder
  SampleItemBuilder(item: SampleContent, index: number) {
    TrackNode() {
      Stack({ alignContent: Alignment.TopStart }) {
        TagTipLabel({
          tags: item.tagIds,
          newSymbol: $r('app.media.big_new'),
        })
          .margin({
            top: $r('sys.float.padding_level3'),
            left: $r('sys.float.padding_level3'),
          })
          .width(CommonConstants.FULL_PERCENT)

        Column() {
          Column() {
            ImageComponent({
              src: item.mediaInfoList[0].mediaUrl,
              objectFit: ImageFit.Contain,
              alt: $r('app.media.img_placeholder'),
            })
              .height('100%')
          }
          .layoutWeight(1)

          Column() {
            Text(item.title)
              .fontSize($r('sys.float.Body_L'))
              .fontWeight(FontWeight.Bold)
              .fontColor($r('sys.color.font_primary'))
            TagLabel({
              tags: item.tags,
              maxWidth: LOG_MAX_WIDTH,
            })
          }
          .width('100%')
          .padding({ top: $r('sys.float.padding_level8') })
          .renderGroup(true)
        }
      }
      .clickEffect({ level: ClickEffectLevel.MIDDLE })
      .onClick(() => this.handleItemClick?.(index, item))
      .padding($r('sys.float.padding_level8'))
      .backgroundColor($r('sys.color.comp_background_list_card'))
      .borderRadius($r('sys.float.corner_radius_level8'))
      .height($r('app.float.card_scroll_height'))
      .width(this.sampleItemWidth)
      .customProperty(TRACK_KEY, {
        interactionContent: item.title,
        interactionType: InteractionTypeEnum.SAMPLE,
      } as TrackServiceData)
    }
  }

  build() {
    Column() {
      Column() {
        Text(this.sampleCardData.title)
          .fontSize($r('sys.float.Subtitle_L'))
          .fontColor($r('sys.color.ohos_id_color_foreground'))
          .fontWeight(FontWeight.Bold)
        Text(this.sampleCardData.subTitle)
          .fontSize($r('sys.float.Body_S'))
          .fontColor($r('sys.color.font_secondary'))
          .fontWeight(FontWeight.Regular)
          .margin({
            top: $r('sys.float.padding_level2'),
            bottom: $r('sys.float.padding_level6'),
          })
      }
      .alignItems(HorizontalAlign.Start)
      .width('100%')
      .padding({
        left: this.horizontalPadding,
        right: this.horizontalPadding,
      })

      List({ space: CommonConstants.SPACE_16 }) {
        Repeat(this.sampleCardData.sampleContents).each((repeatItem: RepeatItem<SampleContent>) => {
          ListItem() {
            this.SampleItemBuilder(repeatItem.item, repeatItem.index)
          }
        })
          .virtualScroll()
          .key((item: SampleContent) => item.id.toString())
      }
      .cachedCount(3)
      .contentStartOffset(this.contentOffset)
      .contentEndOffset(this.contentOffset)
      .scrollBar(BarState.Off)
      .listDirection(Axis.Horizontal)
      .width('100%')
      .height($r('app.float.card_scroll_height'))
    }
    .alignItems(HorizontalAlign.Start)
  }
}