/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const CITY_DATA: TextCascadePickerRangeContent[] = [
  {
    text: 'Hubei',
    children: [
      {
        text: 'Wuhan',
        children: [
          { text: 'Jiang\'an' },
          { text: 'Jianghan' },
          { text: 'Qiaokou' },
          { text: 'Hanyang' },
          { text: 'Wuchang' },
          { text: 'Qingshan' },
          { text: 'Hongshan' },
          { text: 'Dongxihu' },
          { text: 'Caidian' },
          { text: 'Jiangxia' },
          { text: 'Huangpi' },
          { text: 'Xinzhou' }
        ]
      },
      {
        text: 'Xiaogan',
        children: [
          { text: 'Xiaonan' },
          { text: 'Xiaochang' },
          { text: 'Dawu' },
          { text: 'Yunmeng' },
          { text: 'Yingcheng' },
          { text: 'Anlu' },
          { text: 'Hanchuan' }
        ]
      },
      {
        text: 'Huanggang',
        children: [
          { text: 'Huangzhou' },
          { text: 'Tuanfeng' },
          { text: 'Hong\'an' },
          { text: 'Luotian' },
          { text: 'Yingshan' },
          { text: 'Xishui' },
          { text: 'Qichun' },
          { text: 'Huangmei' },
          { text: 'Macheng' },
          { text: 'Wuxue' }
        ]
      }
    ]
  },
  {
    text: 'Hunan',
    children: [
      {
        text: 'Changsha',
        children: [
          { text: 'Furong' },
          { text: 'Tianxin' },
          { text: 'Yuelu' },
          { text: 'Kaifu' },
          { text: 'Yuhua' },
          { text: 'Wangcheng' },
          { text: 'Changsha' },
          { text: 'Liuyang' },
          { text: 'Ningxiang' }
        ]
      },
      {
        text: 'Zhuzhou',
        children: [
          { text: 'Tianyuan' },
          { text: 'Hetang' },
          { text: 'Lusong' },
          { text: 'Shifeng' },
          { text: 'Yanling' },
          { text: 'Chaling' },
          { text: 'You' },
          { text: 'Liling' }
        ]
      },
      {
        text: 'Xiangtan',
        children: [
          { text: 'Yuetang' },
          { text: 'Yuhu' },
          { text: 'Xiangtan' },
          { text: 'Shaoshan' },
          { text: 'Xiangxiang' }
        ]
      }
    ]
  },
  {
    text: 'Jiangsu',
    children: [
      {
        text: 'Nanjing',
        children: [
          { text: 'Xuanwu' },
          { text: 'Qinhuai' },
          { text: 'Jianye' },
          { text: 'Gulou' },
          { text: 'Pukou' },
          { text: 'Qixia' },
          { text: 'Yuhuatai' },
          { text: 'Jiangning' },
          { text: 'Liuhe' },
          { text: 'Lishui' },
          { text: 'Gaochun' }
        ]
      },
      {
        text: 'Suzhou',
        children: [
          { text: 'Gusu' },
          { text: 'Wuzhong' },
          { text: 'Xiangcheng' },
          { text: 'Kunshan' },
          { text: 'Taicang' },
          { text: 'Changshu' },
          { text: 'Zhangjiagang' }
        ]
      },
      {
        text: 'Wuxi',
        children: [
          { text: 'Binhu' },
          { text: 'Liangxi' },
          { text: 'Xishan' },
          { text: 'Huishan' },
          { text: 'Jiangyin' },
          { text: 'Yixing' }
        ]
      }
    ]
  },
  {
    text: 'Guangdong',
    children: [
      {
        text: 'Guangzhou',
        children: [
          { text: 'Liwan' },
          { text: 'Yuexiu' },
          { text: 'Haizhu' },
          { text: 'Tianhe' },
          { text: 'Baiyun' },
          { text: 'Huangpu' },
          { text: 'Panyu' },
          { text: 'Huadu' },
          { text: 'Nansha' },
          { text: 'Conghua' },
          { text: 'Zengcheng' }
        ]
      },
      {
        text: 'Shenzhen',
        children: [
          { text: 'Luohu' },
          { text: 'Futian' },
          { text: 'Nanshan' },
          { text: 'Bao\'an' },
          { text: 'Longgang' },
          { text: 'Yantian' },
          { text: 'Longhua' },
          { text: 'Pingshan' },
          { text: 'Guangming' }
        ]
      },
      {
        text: 'Dongguan',
        children: [
          { text: 'Dongguan' }
        ]
      }
    ]
  },
  {
    text: 'Sichuan',
    children: [
      {
        text: 'Chengdu',
        children: [
          { text: 'Jinjiang' },
          { text: 'Qingyang' },
          { text: 'Jinniu' },
          { text: 'Wuhou' },
          { text: 'Chenghua' },
          { text: 'Qingbaijiang' },
          { text: 'Xindu' },
          { text: 'Wenjiang' },
          { text: 'Shuangliu' },
          { text: 'Pidu' },
          { text: 'Longquanyi' }
        ]
      },
      {
        text: 'Mianyang',
        children: [
          { text: 'Fucheng' },
          { text: 'Youxian' },
          { text: 'Anzhou' },
          { text: 'Jiangyou' }
        ]
      },
      {
        text: 'Deyang',
        children: [
          { text: 'Jingyang' },
          { text: 'Luojiang' },
          { text: 'Guanghan' },
          { text: 'Shifang' },
          { text: 'Mianzhu' }
        ]
      }
    ]
  }
];