/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class SpaceToken {
  /**
   * Spacing: 0vp
   */
  public static readonly SPACE_0: number = 0;

  /**
   * Spacing: 1.5vp
   */
  public static readonly SPACE_1_POINT_5: number = 1.5;

  /**
   * Spacing: 2vp
   */
  public static readonly SPACE_2: number = 2;

  /**
   * Spacing: 4vp
   */
  public static readonly SPACE_4: number = 4;

  /**
   * Spacing: 6vp
   */
  public static readonly SPACE_6: number = 6;

  /**
   * Spacing: 7vp
   */
  public static readonly SPACE_7: number = 7;

  /**
   * Spacing: 8vp
   */
  public static readonly SPACE_8: number = 8;

  /**
   * Spacing: 8.75vp
   */
  public static readonly SPACE_8_point_75VP: number = 8.75;

  /**
   * Spacing: 9vp
   */
  public static readonly SPACE_9: number = 9;

  /**
   * Spacing: 10vp
   */
  public static readonly SPACE_10: number = 10;

  /**
   * Spacing: 12vp
   */
  public static readonly SPACE_12: number = 12;

  /**
   * Spacing: 16vp
   */
  public static readonly SPACE_16: number = 16;

  /**
   * Spacing: 24vp
   */
  public static readonly SPACE_24: number = 24;

  /**
   * Spacing: 26vp
   */
  public static readonly SPACE_26: number = 26;

  /**
   * Spacing: 28vp
   */
  public static readonly SPACE_28: number = 28;


  /**
   * Spacing: 30vp
   */
  public static readonly SPACE_30: number = 30;

  /**
   * Spacing: 32vp
   */
  public static readonly SPACE_32: number = 32;
  /**
   * Spacing: 36vp
   */
  public static readonly SPACE_36: number = 36;

  /**
   * Spacing: 44vp
   */
  public static readonly SPACE_44: number = 44;
  /**
   * Spacing: 60vp
   */
  public static readonly SPACE_60: number = 60;
}
