/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { GridItemData } from '../model/GridData';

export const GRID_MENU_DATA_LIST: GridItemData[] = [
  {
    id: 1,
    title: $r('app.string.title_label'),
    imageRes: $r('sys.symbol.heart_fill')
  },
  {
    id: 2,
    title: $r('app.string.title_label'),
    imageRes: $r('sys.symbol.moon_fill')
  },
  {
    id: 3,
    title: $r('app.string.title_label'),
    imageRes: $r('sys.symbol.calendar_fill')
  },
  {
    id: 4,
    title: $r('app.string.title_label'),
    imageRes: $r('sys.symbol.worldclock_fill')
  },
  {
    id: 5,
    title: $r('app.string.title_label'),
    imageRes: $r('sys.symbol.camera_filters_fill')
  },
  {
    id: 6,
    title: $r('app.string.title_label'),
    imageRes: $r('sys.symbol.bolt_shield_fill')
  },
  {
    id: 7,
    title: $r('app.string.title_label'),
    imageRes: $r('sys.symbol.movie_fill')
  },
  {
    id: 8,
    title: $r('app.string.title_label'),
    imageRes: $r('sys.symbol.book_pages_fill_1')
  },
  {
    id: 9,
    title: $r('app.string.title_label'),
    imageRes: $r('sys.symbol.discover_fill')
  },
  {
    id: 10,
    title: $r('app.string.title_label'),
    imageRes: $r('sys.symbol.envelope_fill')
  }
];

export const GRID_CONTENT_DATA_LIST: GridItemData[] = [
  {
    id: 1,
    title: $r('app.string.title_label'),
    imageRes: $r('app.media.img_11'),
    subtitle: $r('app.string.description_label')
  },
  {
    id: 2,
    title: $r('app.string.title_label'),
    imageRes: $r('app.media.img_10'),
    subtitle: $r('app.string.description_label')
  },
  {
    id: 3,
    title: $r('app.string.title_label'),
    imageRes: $r('app.media.img_5'),
    subtitle: $r('app.string.description_label')
  },
  {
    id: 4,
    title: $r('app.string.title_label'),
    imageRes: $r('app.media.img_17'),
    subtitle: $r('app.string.description_label')
  }
];